In [1]:
## Reading the preprocessed dataset 
import pandas as pd
df1 = pd.read_csv(r'/Users/noortje/Documents/880502-M-18 | Master Thesis/Python/RQ1 dataset.csv')

## Reviewing the loaded dataset
df1

        male  education  distance_store  health_status
0      685.0      0.032           0.266              0
1      616.0      0.034           0.297              0
2      713.0      0.142           0.267              0
3      604.0      0.321           0.075              0
4     1040.0      0.325           0.483              0
...      ...        ...             ...            ...
4831   784.0      0.406           0.354              0
4832   693.0      0.276           1.574              0
4833   880.0      0.431           0.652              0
4834   789.0      0.232           0.780              0
4835   915.0      0.283           0.431              0

[4836 rows x 4 columns]

In [2]:
## Reading the preprocessed dataset 
import pandas as pd
df2 = pd.read_csv(r'/Users/noortje/Documents/880502-M-18 | Master Thesis/Python/RQ2 dataset.csv')

## Reviewing the loaded dataset
df2

,f_beer,f_dairy,f_eggs,f_fats_oils,f_meat_red,f_sauces,f_spirits,f_sweets,f_tea_coffee,f_water,f_wine,health_status
0,0.017064,0.136988,0.012324,0.020540,0.047401,0.010744,0.002844,0.117238,0.004898,0.016906,0.035709,0
1,0.010780,0.122793,0.013592,0.021559,0.039681,0.007655,0.003281,0.147477,0.005468,0.020934,0.032807,0
2,0.012287,0.144925,0.016664,0.021882,0.037872,0.006228,0.002525,0.133479,0.005555,0.022218,0.035516,0
3,0.012327,0.154237,0.009245,0.022034,0.047920,0.009091,0.002773,0.131741,0.004622,0.014792,0.025732,0
4,0.020667,0.127989,0.012105,0.021258,0.042663,0.008119,0.002657,0.124594,0.002214,0.022586,0.040301,0
...,...,...,...,...,...,...,...,...,...,...,...,...
51290,0.021021,0.060060,0.003003,0.018018,0.012012,0.009009,0.009009,0.276276,0.003003,0.003003,0.003003,0
51291,0.011080,0.138504,0.002770,0.033241,0.016620,0.005540,0.002770,0.174515,0.016620,0.016620,0.002770,0
51292,0.004988,0.122195,0.007481,0.009975,0.017456,0.004988,0.007481,0.174564,0.022444,0.042394,0.012469,0
51293,0.030369,0.104121,0.002169,0.006508,0.049892,0.002169,0.002169,0.197397,0.015184,0.021692,0.004338,0
51294,0.020134,0.102908,0.017897,0.046980,0.022371,0.004474,0.006711,0.196868,0.004474,0.031320,0.011186,0

In [6]:
## Reading the preprocessed dataset 
import pandas as pd
df4 = pd.read_csv(r'/Users/noortje/Documents/880502-M-18 | Master Thesis/Python/Dataset RQ4.csv')

## Reviewing the loaded dataset
df4

        male  education  distance_store  health_status
0      805.0      0.093           0.269              0
1     1213.0      0.281           0.601              0
2      930.0      0.299           0.310              0
3      913.0      0.190           0.396              0
4      788.0      0.296           0.222              0
...      ...        ...             ...            ...
4831   989.0      0.138           0.418              1
4832   856.0      0.093           0.299              1
4833   729.0      0.351           0.775              1
4834   863.0      0.257           0.256              1
4835   725.0      0.100           0.066              1

[4836 rows x 4 columns]

In [3]:
## DUMMYCLASSIFIER FOR RQ1 DATASET
from sklearn.dummy import DummyClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import recall_score, balanced_accuracy_score
from imblearn.over_sampling import SMOTE
from sklearn.preprocessing import RobustScaler
import numpy as np

## Assign data to X and Y
X = df1.drop('health_status', axis=1).values
Y = df1['health_status'].values

## Splitting the data into a training and testing set
X_train, X_test, y_train, y_test = train_test_split(X, Y, 
test_size = 0.23, stratify = Y)

## Feature scaling using RobustScaler to put all features to the same scale
scaler = RobustScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

## Implementing SMOTE on training data, to train the model on a balanced dataset
smote = SMOTE(random_state=101, sampling_strategy = 'minority')
X_res, y_res = smote.fit_resample(X_train, y_train)

## Assigning sample weights
weights = np.zeros(len(y_res))
weights[y_res == 1] = 0.991
weights[y_res == 0] = 0.009

## Defining and fitting the model
model = DummyClassifier(random_state = 101, strategy = 'most_frequent')
model.fit(X_res, y_res)

## Making predictions for the dummy on testing data
pred = model.predict(X_test)

## Evaluating the baseline score
print('Baseline Recall-score (positive class) =', recall_score(y_test, pred, pos_label = 1))
print('Baseline Balanced Accuracy Score =', balanced_accuracy_score(y_test, pred))

Baseline Recall-score (positive class) = 0.0
Baseline Balanced Accuracy Score = 0.5

In [4]:
## DUMMYCLASSIFIER FOR RQ2 DATASET
from sklearn.dummy import DummyClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import recall_score, balanced_accuracy_score
from imblearn.over_sampling import SMOTE
from sklearn.preprocessing import RobustScaler
import numpy as np

## Assign data to X and Y
X = df2.drop('health_status', axis=1).values
Y = df2['health_status'].values

## Splitting the data into a training and testing set
X_train, X_test, y_train, y_test = train_test_split(X, Y, 
test_size = 0.18, stratify = Y)

## Feature scaling using RobustScaler to put all features to the same scale
scaler = RobustScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

## Implementing SMOTE on training data, to train the model on a balanced dataset
smote = SMOTE(random_state=101, sampling_strategy = 'minority')
X_res, y_res = smote.fit_resample(X_train, y_train)

## Assigning sample weights
weights = np.zeros(len(y_res))
weights[y_res == 1] = 0.999
weights[y_res == 0] = 0.001

## Defining and fitting the model
model = DummyClassifier(random_state = 101, strategy = 'most_frequent')
model.fit(X_res, y_res)

## Making predictions for the dummy on testing data
pred = model.predict(X_test)

## Evaluating the baseline score
print('Baseline Recall-score (positive class) =', recall_score(y_test, pred, pos_label = 1))
print('Baseline Balanced Accuracy Score =', balanced_accuracy_score(y_test, pred))

Baseline Recall-score (positive class) = 0.0
Baseline Balanced Accuracy Score = 0.5

In [8]:
## DUMMYCLASSIFIER FOR RQ4 DATASET
from sklearn.dummy import DummyClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import recall_score, balanced_accuracy_score
from imblearn.over_sampling import SMOTE
from sklearn.preprocessing import RobustScaler
import numpy as np

## Assign data to X and Y
X = df4.drop('health_status', axis=1).values
Y = df4['health_status'].values

## Splitting the data into a training and testing set
X_train, X_test, y_train, y_test = train_test_split(X, Y, 
test_size = 0.23)

## Feature scaling using RobustScaler to put all features to the same scale
scaler = RobustScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

## Assigning sample weights
weights = np.zeros(len(y_res))
weights[y_res == 1] = 0.5
weights[y_res == 0] = 0.5

## Defining and fitting the model
model = DummyClassifier(random_state = 101, strategy = 'most_frequent')
model.fit(X_train, y_train)

## Making predictions for the dummy on testing data
pred = model.predict(X_test)

## Evaluating the baseline score
print('Baseline Recall-score (positive class) =', recall_score(y_test, pred, pos_label = 1))
print('Baseline Balanced Accuracy Score =', balanced_accuracy_score(y_test, pred))

Baseline Recall-score (positive class) = 0.0
Baseline Balanced Accuracy Score = 0.5